//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCIMS
{
    public partial class Site
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
/*
namespace PSCIMS
{
    public partial class Site
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// TitleContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// LoginName1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LoginName LoginName1;

        /// <summary>
        /// LoginStatus1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LoginStatus LoginStatus1;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}*/