//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCIMS.jobs
{
    public partial class ActiveAdvertsInternsInternshipExt
    {
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlMinistry;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.PlaceHolder phEmpty;
        protected global::System.Web.UI.WebControls.Button btnClearFilters;

        protected global::System.Web.UI.WebControls.PlaceHolder phList;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Repeater rptInternships;
    }
}