//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCIMS.jobs
{
    public partial class AdvertStatusGlobal
    {
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.PlaceHolder phEmpty;
        protected global::System.Web.UI.WebControls.Button btnClearFilters;

        protected global::System.Web.UI.WebControls.PlaceHolder phList;
        protected global::System.Web.UI.WebControls.Repeater rptStatus;
    }
}