//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCIMS.jobs
{
    public partial class DefaultPartial { }
}