//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCIMS.jobs
{
    public partial class Error
    {
        protected global::System.Web.UI.WebControls.Literal litMessage;
    }
}